// <auto-generated />
using System;
using CryptLearn.Modules.ModuleSolving.Core.DAL.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptLearn.Modules.ModuleSolving.Core.DAL.Migrations
{
    [DbContext(typeof(ModuleSolvingDbContext))]
    [Migration("20231111135426_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CryptLearn.Modules.ModuleSolving.Core.Entities.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AthorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("CryptLearn.Modules.ModuleSolving.Core.Entities.Solution", b =>
                {
                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModuleId", "UserId", "Language");

                    b.ToTable("Solutions");
                });

            modelBuilder.Entity("CryptLearn.Modules.ModuleSolving.Core.Entities.Test", b =>
                {
                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModuleId", "Language");

                    b.ToTable("Test");
                });

            modelBuilder.Entity("CryptLearn.Modules.ModuleSolving.Core.Entities.Solution", b =>
                {
                    b.HasOne("CryptLearn.Modules.ModuleSolving.Core.Entities.Module", null)
                        .WithMany("Solutions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptLearn.Modules.ModuleSolving.Core.Entities.Test", b =>
                {
                    b.HasOne("CryptLearn.Modules.ModuleSolving.Core.Entities.Module", null)
                        .WithMany("Tests")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptLearn.Modules.ModuleSolving.Core.Entities.Module", b =>
                {
                    b.Navigation("Solutions");

                    b.Navigation("Tests");
                });
#pragma warning restore 612, 618
        }
    }
}
